import {
  Application,
  BatchRenderer,
  BatchShaderGenerator,
  Bounds,
  Circle,
  Container,
  DisplayObject,
  FederatedEvent,
  Filter,
  Geometry,
  Graphics,
  GraphicsGeometry,
  IPointData,
  Matrix,
  Mesh,
  Point,
  Polygon,
  Program,
  Rectangle,
  RenderTexture,
  Renderer,
  Sprite,
  Text,
  TextStyle,
  Texture,
  Transform,
} from 'pixi.js';

declare global {
  namespace PIXI {
    export {
      Application,
      BatchRenderer,
      BatchShaderGenerator,
      Bounds,
      Circle,
      Container,
      DisplayObject,
      FederatedEvent,
      Filter,
      Geometry,
      Graphics,
      GraphicsGeometry,
      IPointData,
      Matrix,
      Mesh,
      Point,
      Polygon,
      Program,
      Rectangle,
      Renderer,
      RenderTexture,
      Sprite,
      Text,
      TextStyle,
      Texture,
      Transform,
    };
  }
}
